configure:
  languages:
{{- if .Computed.javascript }}
    javascript: true
{{- end}}

lint:
  aspects:
    - //tools/lint:linters.bzl%shellcheck
{{- if .Computed.javascript }}
    - //tools/lint:linters.bzl%eslint
{{- end }}
{{- if .Computed.python }}
    - //tools/lint:linters.bzl%ruff
{{- end }}
