# Backstage catalog-info.yaml
# See https://backstage.io/docs/features/software-catalog/descriptor-format
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  # Note: {{ "{{" }} .ProjectKebab {{ "}}" }} will be replaced by scaffold with the project name
{{- if .Computed.kitchen_sink }}
  name: kitchen-sink-generated-blueprint
{{- else if .Computed.minimal }}
  name: minimal-generated-blueprint
{{- else if .Computed.javascript }}
  name: javascript-generated-blueprint
{{- else if .Computed.python }}
  name: python-generated-blueprint
{{- else if .Computed.go }}
  name: go-generated-blueprint
{{- else if .Computed.java }}
  name: java-generated-blueprint
{{- else if .Computed.kotlin }}
  name: kotlin-generated-blueprint
{{- else if .Computed.cpp }}
  name: cpp-generated-blueprint
{{- else if .Computed.rust }}
  name: rust-generated-blueprint
{{- else if .Computed.shell }}
  name: shell-generated-blueprint
{{- else }}
  name: {{ .ProjectSnake }}
{{- end }}
  # title: Generated Kitchen-Sink Application Template
  description: Bazel project using Aspect Workflows
  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    backstage.io/techdocs-ref: dir:.
    # backstage.io/source-template: template:default/springboot-template
  tags:
    - bazel
    - aspect-workflows
{{- if .Computed.kitchen_sink }}
    - kitchen-sink
    - multi-language
{{- else if .Computed.minimal }}
    - minimal
{{- end }}
{{- if .Computed.javascript }}
    - javascript
    - typescript
{{- end }}
{{- if .Computed.python }}
    - python
{{- end }}
{{- if .Computed.go }}
    - go
{{- end }}
{{- if .Computed.java }}
    - java
{{- end }}
{{- if .Computed.kotlin }}
    - kotlin
{{- end }}
{{- if .Computed.cpp }}
    - cpp
{{- end }}
{{- if .Computed.rust }}
    - rust
{{- end }}
{{- if .Computed.shell }}
    - shell
{{- end }}
  links:
{{- if .Computed.kitchen_sink }}
    - url: https://github.com/BlueCentre/kitchen-sink
{{- else if .Computed.minimal }}
    - url: https://github.com/BlueCentre/minimal
{{- else if .Computed.javascript }}
    - url: https://github.com/BlueCentre/javascript
{{- else if .Computed.python }}
    - url: https://github.com/BlueCentre/python
{{- else if .Computed.go }}
    - url: https://github.com/BlueCentre/go
{{- else if .Computed.java }}
    - url: https://github.com/BlueCentre/java
{{- else if .Computed.kotlin }}
    - url: https://github.com/BlueCentre/kotlin
{{- else if .Computed.cpp }}
    - url: https://github.com/BlueCentre/cpp
{{- else if .Computed.rust }}
    - url: https://github.com/BlueCentre/rust
{{- else if .Computed.shell }}
    - url: https://github.com/BlueCentre/shell
{{- else }}
    - url: https://github.com/BlueCentre/unknown
{{- end }}
      title: Repository
      icon: github
spec:
  type: template
  system: software-foundation
  lifecycle: experimental
  # TODO: Update owner to match your team/organization
  owner: team-platform
  # dependsOn:
  #   - compontent:default/aspect-workflows-template
  subcomponentOf: application-blueprint-generator
