{{- if .Scaffold.backstage }}
# Backstage catalog-info.yaml
# This file registers the Template itself in Backstage's catalog
# See https://backstage.io/docs/features/software-templates/
apiVersion: scaffolder.backstage.io/v1beta3
kind: Location
metadata:
  name: aspect-workflows-templates
  description: Aspect Workflows Bazel Monorepo Templates
spec:
  type: url
  targets:
    - ./template.yaml
{{- else }}
# Backstage catalog-info.yaml
# See https://backstage.io/docs/features/software-catalog/descriptor-format
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  # Note: {{ "{{" }} .ProjectKebab {{ "}}" }} will be replaced by scaffold with the project name
{{- if .Computed.kitchen_sink }}
  name: kitchen-sink-generated-project
{{- else if .Computed.minimal }}
  name: minimal-generated-project
{{- else if .Computed.javascript }}
  name: javascript-generated-project
{{- else if .Computed.python }}
  name: python-generated-project
{{- else if .Computed.go }}
  name: go-generated-project
{{- else if .Computed.java }}
  name: java-generated-project
{{- else if .Computed.kotlin }}
  name: kotlin-generated-project
{{- else if .Computed.cpp }}
  name: cpp-generated-project
{{- else if .Computed.rust }}
  name: rust-generated-project
{{- else if .Computed.shell }}
  name: shell-generated-project
{{- else }}
  name: {{ .ProjectSnake }}
{{- end }}
  description: Bazel project using Aspect Workflows
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - bazel
    - aspect-workflows
{{- if .Computed.kitchen_sink }}
    - kitchen-sink
    - multi-language
{{- else if .Computed.minimal }}
    - minimal
{{- end }}
{{- if .Computed.javascript }}
    - javascript
    - typescript
{{- end }}
{{- if .Computed.python }}
    - python
{{- end }}
{{- if .Computed.go }}
    - go
{{- end }}
{{- if .Computed.java }}
    - java
{{- end }}
{{- if .Computed.kotlin }}
    - kotlin
{{- end }}
{{- if .Computed.cpp }}
    - cpp
{{- end }}
{{- if .Computed.rust }}
    - rust
{{- end }}
{{- if .Computed.shell }}
    - shell
{{- end }}
  links:
    - url: https://github.com/BlueCentre/{{ .ProjectSnake }}
      title: Repository
      icon: github
    - url: https://docs.aspect.build/
      title: Aspect Documentation
      icon: docs

spec:
  type: service
  lifecycle: experimental
  owner: team-platform
  system: {{ .ProjectSnake }}
{{- end }}
